In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

In [ ]:
np.show_config()

In [32]:
# Generates random number based on a range 
np.random.randint(0, 99, size=(2, 3, 5)).shape # The 0-99 is the range

(2, 3, 5)

In [31]:
np.random.randn(2, 3, 5).shape # Generates random number with the specified shape from a normal distribution

(2, 3, 5)

In [30]:
# Generates random number with the specified shape from a uniform distribution over [0, 1)
np.random.rand(2, 3, 5).shape

(2, 3, 5)

In [29]:
np.random.random((2,3,5)).shape

(2, 3, 5)

In [35]:
# Generates random number based on a range 
a = np.random.randint(0, 99, size=(2, 3, 5)) # The 0-99 is the range
a

array([[[96, 95, 51, 52, 77],
        [82, 32, 58, 63, 80],
        [10, 34, 82,  5, 41]],

       [[ 0, 70, 87, 77, 98],
        [13, 30, 42, 23,  4],
        [27, 42, 93, 51, 97]]])

In [36]:
print(a)

[[[96 95 51 52 77]
  [82 32 58 63 80]
  [10 34 82  5 41]]

 [[ 0 70 87 77 98]
  [13 30 42 23  4]
  [27 42 93 51 97]]]


In [37]:
np.ones((5, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:

np.full((5, 2, 3),1)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [42]:
np.random.randint(1, 2, size=(5, 2, 3))

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [43]:
a.size

30

In [44]:
a.shape

(2, 3, 5)

In [45]:
b.transpose()

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [46]:
b.reshape(2,3,5)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [50]:
c = b.T
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [51]:
print(a.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)


In [52]:
d = a + c
d

array([[[97, 96, 52, 53, 78],
        [83, 33, 59, 64, 81],
        [11, 35, 83,  6, 42]],

       [[ 1, 71, 88, 78, 99],
        [14, 31, 43, 24,  5],
        [28, 43, 94, 52, 98]]])

In [53]:
print('a: ', a)
print('d: ', d)

a:  [[[96 95 51 52 77]
  [82 32 58 63 80]
  [10 34 82  5 41]]

 [[ 0 70 87 77 98]
  [13 30 42 23  4]
  [27 42 93 51 97]]]
d:  [[[97 96 52 53 78]
  [83 33 59 64 81]
  [11 35 83  6 42]]

 [[ 1 71 88 78 99]
  [14 31 43 24  5]
  [28 43 94 52 98]]]


In [55]:
e = a * c
e

array([[[96, 95, 51, 52, 77],
        [82, 32, 58, 63, 80],
        [10, 34, 82,  5, 41]],

       [[ 0, 70, 87, 77, 98],
        [13, 30, 42, 23,  4],
        [27, 42, 93, 51, 97]]])

In [56]:
print(a == e)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [57]:
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

99
1
54.733333333333334


In [60]:
f = np.empty((2, 3, 5))
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [61]:
for x in range(2):
    for y in range(3):        
        for z in range(5):
           
            d_value = d[x, y, z] 

            if d_min < d_value < d_mean:
                f[x, y, z] = 25

            elif d_value == d_mean:
                f[x, y, z] = 50

            elif d_mean < d_value < d_max:
                f[x, y, z] = 75

            elif d_value == d_min:
                f[x, y, z] = 0

            elif d_value == d_max:
                f[x, y, z] = 100

In [62]:
f

array([[[ 75.,  75.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  75.,  25.,  25.]],

       [[  0.,  75.,  75.,  75., 100.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  75.]]])

In [63]:
print('d: ', d)
print('f: ', f)

d:  [[[97 96 52 53 78]
  [83 33 59 64 81]
  [11 35 83  6 42]]

 [[ 1 71 88 78 99]
  [14 31 43 24  5]
  [28 43 94 52 98]]]
f:  [[[ 75.  75.  25.  25.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.  75.  25.  25.]]

 [[  0.  75.  75.  75. 100.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]


In [65]:
f

array([[[ 75.,  75.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  25.,  75.,  25.,  25.]],

       [[  0.,  75.,  75.,  75., 100.],
        [ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  75.,  25.,  75.]]])

In [68]:
g = np.empty((2, 3, 5), dtype='str')

for x in range(2):
    for y in range(3):        
        for z in range(5):
           
            d_value = d[x, y, z] 

            if d_min < d_value < d_mean:
                g[x, y, z] = 'B'

            elif d_value == d_mean:
                g[x, y, z] = 'C'

            elif d_mean < d_value < d_max:
                g[x, y, z] = 'D'

            elif d_value == d_min:
                g[x, y, z] = 'A'

            elif d_value == d_max:
                g[x, y, z] = 'E'

In [69]:
g

array([[['D', 'D', 'B', 'B', 'D'],
        ['D', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'D', 'B', 'B']],

       [['A', 'D', 'D', 'D', 'E'],
        ['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'D', 'B', 'D']]], dtype='<U1')