In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/franpc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/franpc/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/franpc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/franpc/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/franpc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/franpc/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/franpc/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/franpc/anaconda3\\Library\\include']


In [4]:
# Generates random number based on a range 
np.random.randint(0, 99, size=(2, 3, 5)).shape # The 0-99 is the range

(2, 3, 5)

In [5]:
np.random.randn(2, 3, 5).shape # Generates random number with the specified shape from a normal distribution

(2, 3, 5)

In [6]:
# Generates random number with the specified shape from a uniform distribution over [0, 1)
np.random.rand(2, 3, 5).shape

(2, 3, 5)

In [7]:
np.random.random((2,3,5)).shape

(2, 3, 5)

In [8]:
# Generates random number based on a range 
a = np.random.randint(0, 99, size=(2, 3, 5)) # The 0-99 is the range
a

array([[[78,  9, 29, 14, 21],
        [46, 35, 36, 95,  2],
        [ 6, 86, 66, 12, 82]],

       [[ 5, 90, 65, 42, 75],
        [69, 76, 74, 67,  1],
        [59, 57, 94, 33, 72]]])

In [9]:
print(a)

[[[78  9 29 14 21]
  [46 35 36 95  2]
  [ 6 86 66 12 82]]

 [[ 5 90 65 42 75]
  [69 76 74 67  1]
  [59 57 94 33 72]]]


In [10]:
np.ones((5, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:

np.full((5, 2, 3),1)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [12]:
np.random.randint(1, 2, size=(5, 2, 3))

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [13]:
a.size

30

In [14]:
a.shape

(2, 3, 5)

In [20]:
b = np.random.randint(1, 2, size=(5, 2, 3))

In [21]:
b.reshape(2,3,5)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [29]:
c = b.reshape(2,3,5)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [30]:
print(a.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)


In [31]:
d = a + c
d

array([[[79, 10, 30, 15, 22],
        [47, 36, 37, 96,  3],
        [ 7, 87, 67, 13, 83]],

       [[ 6, 91, 66, 43, 76],
        [70, 77, 75, 68,  2],
        [60, 58, 95, 34, 73]]])

In [32]:
print('a: ', a)
print('d: ', d)

a:  [[[78  9 29 14 21]
  [46 35 36 95  2]
  [ 6 86 66 12 82]]

 [[ 5 90 65 42 75]
  [69 76 74 67  1]
  [59 57 94 33 72]]]
d:  [[[79 10 30 15 22]
  [47 36 37 96  3]
  [ 7 87 67 13 83]]

 [[ 6 91 66 43 76]
  [70 77 75 68  2]
  [60 58 95 34 73]]]


In [33]:
e = a * c
e

array([[[78,  9, 29, 14, 21],
        [46, 35, 36, 95,  2],
        [ 6, 86, 66, 12, 82]],

       [[ 5, 90, 65, 42, 75],
        [69, 76, 74, 67,  1],
        [59, 57, 94, 33, 72]]])

In [34]:
print(a == e)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [35]:
d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

96
2
50.86666666666667


In [56]:
f = np.empty((2, 3, 5))
f

array([[[ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25., 100.,  25.],
        [ 25.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,   0.],
        [ 75.,  75.,  75.,  25.,  75.]]])

In [57]:
for d1 in range(len(f)):
    for d2 in range(len(f[d1])):        
        for d3 in range(len(f[d1, d2])):
           
            d_value = d[d1, d2, d3] 

            if d_min < d_value < d_mean:
                f[d1, d2, d3]  = 25

            elif d_value == d_mean:
                f[d1, d2, d3] = 50

            elif d_mean < d_value < d_max:
                f[d1, d2, d3] = 75

            elif d_value == d_min:
                f[d1, d2, d3] = 0

            elif d_value == d_max:
                f[d1, d2, d3] = 100

In [58]:
f

array([[[ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25., 100.,  25.],
        [ 25.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,   0.],
        [ 75.,  75.,  75.,  25.,  75.]]])

In [39]:
print('d: ', d)
print('f: ', f)

d:  [[[79 10 30 15 22]
  [47 36 37 96  3]
  [ 7 87 67 13 83]]

 [[ 6 91 66 43 76]
  [70 77 75 68  2]
  [60 58 95 34 73]]]
f:  [[[ 75.  25.  25.  25.  25.]
  [ 25.  25.  25. 100.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  75.  75.  75.   0.]
  [ 75.  75.  75.  25.  75.]]]


In [40]:
f

array([[[ 75.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25., 100.,  25.],
        [ 25.,  75.,  75.,  25.,  75.]],

       [[ 25.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  75.,  75.,   0.],
        [ 75.,  75.,  75.,  25.,  75.]]])

In [62]:
g = np.empty((2, 3, 5), dtype='str')

for d1 in range(len(g)):
    for d2 in range(len(g[d1])):        
        for d3 in range(len(g[d1, d2])):
           
            d_value = d[d1, d2, d3]  

            if d_min < d_value < d_mean:
                g[d1, d2, d3] = 'B'

            elif d_value == d_mean:
                g[d1, d2, d3] = 'C'

            elif d_mean < d_value < d_max:
                g[d1, d2, d3] = 'D'

            elif d_value == d_min:
                g[d1, d2, d3] = 'A'

            elif d_value == d_max:
                g[d1, d2, d3] = 'E'

In [63]:
g

array([[['D', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'E', 'B'],
        ['B', 'D', 'D', 'B', 'D']],

       [['B', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'D', 'D', 'A'],
        ['D', 'D', 'D', 'B', 'D']]], dtype='<U1')